{"cells":[{"cell_type":"markdown","metadata":{"id":"M5p7XqD3IevM"},"source":["# Gestión de errores (Excepciones)\n","\n","En el transcurso de la clases se han encontrado varios tipos de errores en Python, como al intentar dividir entre cero, usar un índice fuera de rango de una cadena o acceder a una variable no definida.\n","\n","Estos errores se conocen como excepciones (Exceptions) en Python, y ocurren cuando el programa encuentra una situación que no puede manejar durante la ejecución.\n","\n","Veamos abajo algunos ejemplos de errores:"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"collapsed":true,"executionInfo":{"elapsed":547,"status":"error","timestamp":1727275461208,"user":{"displayName":"Ninfa Esperanza Delgado Bolivar","userId":"11955648372408696357"},"user_tz":180},"id":"rzsZowL0IevR","outputId":"4ff6b804-fc0d-4c54-d715-8c6520f36653"},"outputs":[{"ename":"ZeroDivisionError","evalue":"division by zero","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-9e1622b385b6>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;36m1\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["1/0"]},{"cell_type":"code","execution_count":4,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"collapsed":true,"executionInfo":{"elapsed":447,"status":"error","timestamp":1727275466066,"user":{"displayName":"Ninfa Esperanza Delgado Bolivar","userId":"11955648372408696357"},"user_tz":180},"id":"qrP5Gw1zIevT","outputId":"fe860e53-5a6a-475d-a78b-3dc87c136585"},"outputs":[{"ename":"NameError","evalue":"name '__alsdfjknnlaklk' is not defined","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-944d36acff4a>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0m__alsdfjknnlaklk\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name '__alsdfjknnlaklk' is not defined"]}],"source":["__alsdfjknnlaklk * 1"]},{"cell_type":"code","execution_count":5,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"collapsed":true,"executionInfo":{"elapsed":460,"status":"error","timestamp":1727275469444,"user":{"displayName":"Ninfa Esperanza Delgado Bolivar","userId":"11955648372408696357"},"user_tz":180},"id":"VMPArbrmIevU","outputId":"771b5109-800c-42f2-bc71-bc4b1240d64d"},"outputs":[{"ename":"IndexError","evalue":"string index out of range","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-029484dc3f38>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;34m\"hola\"\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mIndexError\u001b[0m: string index out of range"]}],"source":["\"hola\"[4]"]},{"cell_type":"markdown","metadata":{"id":"GkvBAw71IevU"},"source":["Estos errores pueden ser \"capturados\" para evitar que el programa se detenga de manera abrupta. Esto se logra utilizando bloques `try/except`, que permiten manejar las excepciones de forma controlada.\n","\n","\n","```python\n","try:\n","    BLOQUE DE CODIGO QUE PUEDE GENERAR EL ERROR\n","except ERROR1:\n","    BLOQUE QUE EJECUTO SI SUCEDE EL ERROR 1\n","except ERROR2:\n","    BLOQUE QUE EJECUTO SI SUCEDE EL ERROR 2\n","except:\n","    BLOQUE QUE EJECUTO SI SUCEDE UN ERROR QUE NO ES ERROR1 o ERROR2 (un else de los ERRORES)\n","finally:\n","    BLOQUE OPCIONAL QUE EJECUTO DESPUÉS DEL BLOQUE try O DEL ERROR\n","```\n","\n","A continuación, veamos un ejemplo de código que valida una entrada, incluyendo el manejo de errores mediante la estructura `try-except`:"]},{"cell_type":"code","execution_count":null,"metadata":{"collapsed":true,"id":"Q2MtURw6IevV","outputId":"1817b320-a77b-4415-ce8d-5d63d1f4f431"},"outputs":[{"ename":"ValueError","evalue":"invalid literal for int() with base 10: 'asd'","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","Cell \u001b[0;32mIn[7], line 4\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m es_valido:\n\u001b[1;32m      3\u001b[0m     ingreso \u001b[38;5;241m=\u001b[39m \u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIngrese un número mayor a cero: \u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m----> 4\u001b[0m     num \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mint\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mingreso\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      5\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m num \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[1;32m      6\u001b[0m         es_valido \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'asd'"]}],"source":["es_valido = False\n","while not es_valido:\n","    ingreso = input(\"Ingrese un número mayor a cero: \")\n","    num = int(ingreso)\n","    if num > 0:\n","        es_valido = True\n","    else:\n","        print(\"Ingreso inválido!!\")\n","print(f\"Ingresó {num}\")\n"]},{"cell_type":"markdown","metadata":{"id":"kebiN4bLIevV"},"source":["Si ingreso un texto inválido que no puede convertirse en un int, el programa generará un error y se detendrá de forma inesperada. A continuación, veamos cómo podemos manejar esta situación usando un bloque `try/except` para evitar que el programa se rompa."]},{"cell_type":"code","execution_count":8,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"collapsed":true,"executionInfo":{"elapsed":20420,"status":"ok","timestamp":1727277029495,"user":{"displayName":"Ninfa Esperanza Delgado Bolivar","userId":"11955648372408696357"},"user_tz":180},"id":"0KIPlKvmIevW","outputId":"a6aef3c6-e35d-4584-bbba-42fc237ebaf0"},"outputs":[{"name":"stdout","output_type":"stream","text":["Ingrese un número mayor a cero: j\n","Ingreso inválido!! j no se puede convertir a int\n","Ingrese un número mayor a cero: 5\n","Ingresó 5\n"]}],"source":["es_valido = False\n","while not es_valido:\n","    try:\n","        ingreso = input(\"Ingrese un número mayor a cero: \")\n","        num = int(ingreso)\n","        if num > 0:\n","            es_valido = True\n","    except ValueError:\n","        print(f\"Ingreso inválido!! {ingreso} no se puede convertir a int\")\n","\n","print(f\"Ingresó {num}\")"]},{"cell_type":"markdown","metadata":{"id":"M1cKMgwpIevW"},"source":["La primera vez ingresé `j` y eso generó una excepción de tipo `ValueError`, la cual fue \"atrapada\" por el bloque `except`. Esto evitó que el programa se detuviera abruptamente y permitió mostrar un mensaje indicando el tipo de error que ocurrió.\n","\n","\n","`NOTA IMPORTANTE:` Si una expresión genera un error, esa expresión no se termina de calcular (no se completa), entonces la variable `num` nunca llega a crearse, y por lo tanto, no podemos usarla dentro del bloque `except`, ya que no existe en ese contexto.\n","\n","Veamos el sigiuente ejemplo:\n"]},{"cell_type":"code","execution_count":null,"metadata":{"collapsed":true,"id":"9puHww5aIevW","outputId":"bc23e04a-a997-496c-b7b1-0f3680d51d08"},"outputs":[{"name":"stdout","output_type":"stream","text":["División por cero!! 1/0\n"]},{"ename":"NameError","evalue":"name 'c' is not defined","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[0;32mIn[12], line 9\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m:\n\u001b[1;32m      7\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDivisión por cero!! \u001b[39m\u001b[38;5;132;01m{\u001b[39;00ma\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mb\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m----> 9\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mY c?:\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[43mc\u001b[49m)\n","\u001b[0;31mNameError\u001b[0m: name 'c' is not defined"]}],"source":["try:\n","    a = 1\n","    b = 0\n","    c = a/b\n","\n","except:\n","    print(f\"División por cero!! {a}/{b}\")\n","\n","print(\"Y c?:\", c)\n"]},{"cell_type":"markdown","metadata":{},"source":["En el ejemplo anterior `c` se crea después de que la división de `a/b` se ha realizado exitosamente, y existe un valor para asignarle. Cualquier error en la división, evita la creación de `c`. "]},{"cell_type":"markdown","metadata":{"id":"7JXSIQKIIevX"},"source":["Si yo no se que tipo de Exception debe atrapar con el except, Puedo asignar la excepción a una variable y luego imprimir la descripción del error."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"QfMDBYzLIevX","outputId":"99fc3ae0-aa23-49e2-917c-40ab6787db30"},"outputs":[{"name":"stdout","output_type":"stream","text":["Hubo un error!! division by zero\n"]}],"source":["try:\n","    a = 1\n","    b = 0\n","    c = a/b\n","\n","except Exception as error :\n","    print(f\"Hubo un error!! {error}\")"]},{"cell_type":"markdown","metadata":{"id":"Y51GpkySIevX"},"source":["El texto `division by zero` es la descrición del error en palabras que Python define para ese tipo de error. `Exception` es un tipo de error que represent a todos los posible errores. O sea, cualquier error que haya en el bloque `try` va a ser capturado.\n","\n","Vamos el ejemplo del ingreso de numeros anterior:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"l3yRaHCZIevY","outputId":"c0d74b88-4b48-4ad4-95eb-6cfcdb8aacdb"},"outputs":[{"name":"stdout","output_type":"stream","text":["Hubo un error. Vuelva a intentarlo!! Error: invalid literal for int() with base 10: 'asd'.\n","Hubo un error. Vuelva a intentarlo!! Error: integer division or modulo by zero.\n","El resultado es 10\n"]}],"source":["es_valido = False\n","while not es_valido:\n","    try:\n","        ingreso = input(\"Ingrese un número mayor a cero: \")\n","        num = int(ingreso)\n","        if num > 0:\n","            es_valido = True\n","        c = 10//num\n","        print(f\"El resultado es {c}\")\n","    except Exception as e:\n","        print(f\"Hubo un error. Vuelva a intentarlo!! Error: {e}.\")\n"]},{"cell_type":"markdown","metadata":{"id":"3HzOyLbZIevY"},"source":["Cuando ustedes crean una función, si durante la ejecución de esta se puede dar un error, pueden generar sus propias Excepciones con el comando `raise`. Veamos la siguiente consigna:\n","\n","`Crear una función que solicite el ingreso de un número entero. La función debe devolver el número ingresado. Si el usuario ingresa algo erroneo, debe informar el error, y volver a pedir un nuevo ingreso. Al tercer intento fallo debe crear una excepción.`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"-RSPz90XIevY"},"outputs":[],"source":["def ingreso_num(prompt):\n","    MAX_INTENTOS = 3\n","    intentos = MAX_INTENTOS\n","    while intentos > 0:\n","        ingreso = input(prompt)\n","        try:\n","            num = int(ingreso)\n","            return num    # Si se ejecuta esta línea es por que la anterior NO falló\n","                          # Puedo retornar un valor y terminar la función desde adentro del try!!\n","\n","        except ValueError:\n","            print(f\"Vuelva a intentar. {ingreso} no se puede convertir en int\")\n","            intentos -= 1\n","\n","    raise Exception(f\"Hubo {MAX_INTENTOS} intentos\")\n","    # Despues del raise, la función deja de ejecutarse\n","    print(\"Esto no se imprime nunca\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"z-hh8_Q4IevY","outputId":"db3fcd8c-2ece-4938-fa6f-039ffc1b5f6e"},"outputs":[{"name":"stdout","output_type":"stream","text":["Vuelva a intentar. qwe no se puede convertir en int\n","Vuelva a intentar. asd no se puede convertir en int\n","Vuelva a intentar. zxc no se puede convertir en int\n"]},{"ename":"Exception","evalue":"Hubo 3 intentos","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mException\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[0;32mIn[20], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Vamos a llamar la función y equivocarnos cuatro veces\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[43mingreso_num\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mIngrese un entero\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n","Cell \u001b[0;32mIn[19], line 15\u001b[0m, in \u001b[0;36mingreso_num\u001b[0;34m(prompt)\u001b[0m\n\u001b[1;32m     12\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mVuelva a intentar. \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mingreso\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m no se puede convertir en int\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     13\u001b[0m         intentos \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[0;32m---> 15\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mHubo \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mMAX_INTENTOS\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m intentos\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     16\u001b[0m \u001b[38;5;66;03m# Despues del raise, la función deja de ejecutarse\u001b[39;00m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mEsto no se imprime nunca\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n","\u001b[0;31mException\u001b[0m: Hubo 3 intentos"]}],"source":["# Vamos a llamar la función y equivocarnos cuatro veces\n","a = ingreso_num(\"Ingrese un entero\")"]},{"cell_type":"markdown","metadata":{"id":"wxAjLampIevZ"},"source":["Fíjense en el error que aparece en la última línea del output. Indica el texto `Hubo 3 intentos`, que corresponde con el texto que el código le pasa al Exception.\n","\n","Si cuando llamo a mi función `ingreso_num` se que puede dar un error, entonces puedo caputar ese error."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Bz6JiTkYIevZ","outputId":"7d1f0120-231d-4c7f-e6e5-33cbc5246dbb"},"outputs":[{"name":"stdout","output_type":"stream","text":["Vuelva a intentar. qwe no se puede convertir en int\n","Vuelva a intentar. asd no se puede convertir en int\n","Vuelva a intentar. zxc no se puede convertir en int\n","Hubo un error. Error: Hubo 3 intentos\n"]}],"source":["try:\n","    # Vamos a llamar la función y equivocarnos cuatro veces\n","    a = ingreso_num(\"Ingrese un entero\")\n","except Exception as e:\n","    print(f\"Hubo un error. Error: {e}\")"]},{"cell_type":"markdown","metadata":{"id":"-O81ZBD0Ieva"},"source":["Esta manera es la forma correcta de gestionar errores dentro del programa. Las funciones deben verificar sus argumentos y en caso de que no sean correctos, generar errores para que el programa principal.\n","\n","Veamos otro ejemplo.\n","\n","`Crear una función que devuelva la posición de un caracter en una cadena. La función recibe dos argumentos:\n","    cadena: str en donde se debe buscar el caracter.\n","    c: str caracter que debo buscar. No puede estar vacío.\n","`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ic1eJHu9Ieva"},"outputs":[],"source":["def index( cadena , c ):\n","    # Controlo que los tipos de datos sean los corrector\n","    if type(cadena) != type(\"str\") or type(c) != type(\"str\"):\n","        raise Exception(\"Los argumentos deben ser del tipo string\")\n","    if c == \"\":\n","        raise Exception(\"El caracter a buscar no puede ser una cadena vacía\")\n","    if len(c) != 1:\n","        raise Exception(\"El caracter a buscar no puede ser una cadena de longitud distinta a 1\")\n","\n","    i=0\n","    while i<len(cadena):\n","        if cadena[i] == c:\n","            return i\n","        i += 1\n","\n","    return None\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ecsDL-_8Ieva","outputId":"0bf1150f-7d2f-4b27-820b-c30776863c2c"},"outputs":[{"name":"stdout","output_type":"stream","text":["Caso 1\n","Los argumentos deben ser del tipo string\n","Caso 2\n","Los argumentos deben ser del tipo string\n","Caso 3\n","El caracter a buscar no puede ser una cadena vacía\n","Caso 4\n","El caracter a buscar no puede ser una cadena de longitud distinta a 1\n","Caso 5 - Valido no lo encuentra\n","No se encontró\n","Caso 6 - Valido lo encuentra\n","Está en la posición 1\n"]}],"source":["print(\"Caso 1\")\n","try:\n","    res = index( 1 , \"a\")\n","except Exception as e:\n","    print(e)\n","print(\"Caso 2\")\n","try:\n","    res = index( \"asd\", 1)\n","except Exception as e:\n","    print(e)\n","print(\"Caso 3\")\n","try:\n","    res = index( \"asd\", \"\")\n","except Exception as e:\n","    print(e)\n","print(\"Caso 4\")\n","try:\n","    res = index( \"asd\", \"asd\")\n","except Exception as e:\n","    print(e)\n","\n","print(\"Caso 5 - Valido no lo encuentra\")\n","try:\n","    res = index( \"aaaaa\", \"b\")\n","    if res == None:\n","        print(\"No se encontró\")\n","    else:\n","        print(\"Está en la posición {res}\")\n","except Exception as e:\n","    print(e)\n","\n","print(\"Caso 6 - Valido lo encuentra\")\n","try:\n","    res = index( \"abcde\", \"b\")\n","    if res == None:\n","        print(\"No se encontró\")\n","    else:\n","        print(f\"Está en la posición {res}\")\n","except Exception as e:\n","    print(e)"]},{"cell_type":"markdown","metadata":{"id":"lYFuSrh5Ieva"},"source":["Esta es la forma correcta de crear funciones que controlen los posibles errores antes de que estos sucedan."]}],"metadata":{"colab":{"provenance":[]},"kernelspec":{"display_name":"Python 3.8.2 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.11"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"5edc29c2ed010d6458d71a83433b383a96a8cbd3efe8531bc90c4b8a5b8bcec9"}}},"nbformat":4,"nbformat_minor":0}
